skip_clone: true

steps:
  # ── Stage 1: Clone from Gitea ──
  - name: clone
    image: alpine/git
    commands:
      - git clone http://192.168.86.23:3000/admin/demo-swf-app-chris.git .
      - echo "✓ Clone successful"

  # ── Stage 7: Container Build ──
  - name: container-build
    image: docker:24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t demo-swf-app-chris:latest .
      - echo "✓ Container build successful"
