skip_clone: true

steps:
  # ── Stage 1: Clone from Gitea ──
  - name: clone
    image: alpine/git
    commands:
      - git clone http://192.168.86.23:3000/admin/demo-swf-app-chris.git .
      - echo "✓ Clone successful"

  # ── Stage 7: Container Build ──
  - name: container-build
    image: plugins/docker
    privileged: true
    settings:
      repo: demo-swf-app-chris
      tags: latest
      dockerfile: Dockerfile
      dry_run: true
