skip_clone: true

steps:
  # ── Stage 1: Clone from Gitea ──
  - name: clone
    image: alpine/git
    commands:
      - git clone http://192.168.86.23:3000/admin/demo-swf-app-chris.git .
      - echo "✓ Clone successful"

  # ── Stage 3: Unit Tests (backend only - debugging) ──
  - name: unit-test-backend
    image: eclipse-temurin:17-jdk
    commands:
      - chmod +x gradlew
      - ./gradlew compileTestJava test -x installFrontend -x buildFrontend -x copyFrontend -x resolveMainClassName --no-daemon
      - echo "✓ Backend tests passed"

#  # ── Stage 2: Build (Gradle + Frontend) ──
#  - name: build
#    image: eclipse-temurin:17-jdk
#    commands:
#      - apt-get update && apt-get install -y npm > /dev/null 2>&1
#      - chmod +x gradlew
#      - ./gradlew build -x test --no-daemon
#      - echo "✓ Build successful"
#
#  - name: unit-test-frontend
#    image: node:18-alpine
#    commands:
#      - cd frontend
#      - npm ci
#      - CI=true npm test -- --watchAll=false
#      - echo "✓ Frontend tests passed"
#
#  # ── Stage 4: SAST (Static Application Security Testing) ──
#  - name: sast-semgrep
#    image: semgrep/semgrep:latest
#    commands:
#      - semgrep scan --config auto --severity ERROR --severity WARNING --no-git --json > semgrep-results.json || true
#      - semgrep scan --config auto --severity ERROR --severity WARNING --no-git 2>&1 | tail -30
#      - echo "✓ SAST scan complete"
#
#  # ── Stage 5: Dependency Scanning ──
#  - name: dependency-scan
#    image: aquasec/trivy:latest
#    commands:
#      - trivy fs --scanners vuln --severity HIGH,CRITICAL . || true
#      - echo "✓ Dependency scan complete"
#
#  # ── Stage 6: Lint ──
#  - name: lint-frontend
#    image: node:18-alpine
#    commands:
#      - cd frontend
#      - npm ci
#      - npx eslint src/ --max-warnings 50 || true
#      - echo "✓ Frontend lint complete"
#
#  # ── Stage 7: Container Build ──
#  - name: container-build
#    image: plugins/docker
#    settings:
#      repo: demo-swf-app-chris
#      tags: latest
#      dockerfile: Dockerfile
#      dry_run: true
#      daemon_off: true
#
#  # ── Stage 8: Container Scan ──
#  - name: container-scan
#    image: aquasec/trivy:latest
#    commands:
#      - trivy image --severity HIGH,CRITICAL demo-swf-app-chris:latest || true
#      - echo "✓ Container scan complete"
